# Generated by Django 5.1.3 on 2024-11-30 19:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentText',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='postText',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
