# Generated by Django 5.1.3 on 2024-11-30 19:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_comment_commenttext_alter_post_posttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentText',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='postText',
            field=tinymce.models.HTMLField(),
        ),
    ]
