# Generated by Django 5.1.3 on 2025-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prenatal', 'Prenatal'), ('postnatal', 'Postnatal')], default='prenatal', max_length=10)),
                ('week', models.PositiveIntegerField(blank=True, help_text='Applicable for prenatal milestones (1-40 weeks).', null=True)),
                ('start_age_months', models.PositiveIntegerField(blank=True, help_text='Start age in months for postnatal milestones.', null=True)),
                ('end_age_months', models.PositiveIntegerField(blank=True, help_text='End age in months for postnatal milestones.', null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='milestone_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='PregnancyDevelopmentMilestone',
        ),
    ]
