# Generated by Django 5.1.3 on 2025-01-26 16:09

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_developmentmilestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentmilestone',
            name='description',
            field=django_bleach.models.BleachField(),
        ),
    ]
