# Generated by Django 5.1.3 on 2024-11-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='isForumMod',
            field=models.BooleanField(default=False),
        ),
    ]
