# Generated by Django 5.1.3 on 2025-01-02 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_siteuser_isforummod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='partnerName',
            field=models.CharField(blank=True, max_length=80, validators=[django.core.validators.RegexValidator(message='Null characters are not allowed.', regex='^[^\\0]*$')]),
        ),
    ]
