version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bumpydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runsslserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/bumpydb

    volumes:
    - ./:/app

volumes:
  postgres_data: