# Generated by Django 5.1.3 on 2025-02-02 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed information about this benefit.')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reduction_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='calculator.benefit')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('numeric', 'Numeric'), ('text', 'Text')], help_text='The data type of the criterion value.', max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='calculator.benefit')),
            ],
        ),
    ]
