# Generated by Django 5.1.3 on 2025-02-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Exact match'), ('gt', 'Greater than'), ('lt', 'Less than'), ('none', 'No comparison')], default='exact', max_length=10),
        ),
    ]
