# Generated by Django 5.1.3 on 2025-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_eligibilitycriteria_match_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitrate',
            name='income_threshold',
        ),
        migrations.RemoveField(
            model_name='benefitrate',
            name='reduction_percentage',
        ),
        migrations.AddField(
            model_name='benefitrate',
            name='income_threshold_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The maximum income for the reduction calculation (e.g., 80000).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='benefitrate',
            name='income_threshold_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The minimum income at which reduction applies (e.g., 60000).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='benefitrate',
            name='income_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Income unit for reduction calculation (e.g., 200 for every £200).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='benefitrate',
            name='reduction_rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage reduction per income unit above the minimum threshold (e.g., 1 for 1%).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='value_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('numeric', 'Numeric'), ('text', 'Text')], max_length=20),
        ),
    ]
