# Generated by Django 5.1.3 on 2025-02-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_benefit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='dependent_benefits',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_for', to='calculator.benefit'),
        ),
    ]
